### ISSUE TITLE
Add A2OJ Ladder Solutions

### ISSUE THREAD

**Issue by HADES-01** [HADES-Temp/jubilant-guide#13]
We need solutions to the following under 1300 A2OJ Ladder Questions

- [x] [69A](http://codeforces.com/problemset/problem/69/A)
- [x] [263A](http://codeforces.com/problemset/problem/263/A)
- [x] [266B](http://codeforces.com/problemset/problem/266/B)
- [x] [32B](http://codeforces.com/problemset/problem/32/B)
- [x] [271A](http://codeforces.com/problemset/problem/271/A)

**Comment by TheJollyNaman** [comment]
Sure, I can do that. 
I would like to work on this!
