### ISSUE TITLE
Add Some A2OJ Question Solutions.

### ISSUE THREAD

**Issue by HADES-01** [HADES-Temp/jubilant-guide#2]
We need solutions to the following under 1300 A2OJ Ladder Questions

- [x] [275A](http://codeforces.com/problemset/problem/275/A)
- [x] [59A](http://codeforces.com/problemset/problem/59/A)
- [x] [281A](http://codeforces.com/problemset/problem/281/A)
- [x] [110A](http://codeforces.com/problemset/problem/281/A)
- [x] [266A](http://codeforces.com/problemset/problem/266/A)

**Note**: Create a new folder to add named A2OJ Ladder

**Comment by TheJollyNaman** [comment]
Heyy, I would like to work on this issue! :D

**Comment by HADES-Temp** [comment]
Fine @TheJollyNaman, You can go ahead and start working on thi issue.
