### ISSUE TITLE
Add some GFG Solutions

### ISSUE THREAD

**Issue by HADES-Temp** [HADES-Temp/jubilant-guide#3]
We need solutions to the following GFG Questions:

- [ ] [Preorder traversal (Iterative)](https://practice.geeksforgeeks.org/problems/preorder-traversal-iterative/1)
- [ ] [Searching in an array where adjacent differ by at most k](https://practice.geeksforgeeks.org/problems/searching-in-an-array-where-adjacent-differ-by-at-most-k0456/1)
- [ ] [Cyclically rotate an array by one](https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1)
- [ ] [Minimum number of jumps](https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1)

**Note**: Create a new folder to add named GFG

**Comment by HADES-Temp** [comment]
Sure @GoyalRohan, You can add the solutions. Please test them beforehand.

**Comment by virajshitole** [comment]
i want to add left rotation in array . can you @HADES-Temp  assign this issue to me
